# Generated by Django 5.1.5 on 2025-11-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajecontacto',
            name='mensaje',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mensajecontacto',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
